stages:
  - build
  - test
  - publish
  
build:
  stage: build
  script:
  - echo "Building some artifacts"

test:
  stage: test
  script:
  - ./runme.sh

publish:
  stage: publish
  script:
  - echo "Publishing the artifacts"
